version: '3.4'

services:
  geta-scheduledjobs-sample-web:
    image: geta-scheduledjobs-sample-web:dev
    build:
      args:
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Geta.ScheduledParameterJob.Sample"
    volumes:
      - C:\Projects\Geta.ScheduledParameterJob\samples\Geta.ScheduledParameterJob.Sample:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"

